
#!/bin/bash
#---------------------------------------------------------------------

# Part 1 PBS Directives

#---------------------------------------------------------------------

#PBS -N pi-vae-latent

#PBS -A GT-awu36

#PBS -l walltime=2:00:00

#PBS -l nodes=2:ppn=2

#PBS -q inferno

#PBS -o results.out

#PBS -j oe

#PBS -m abe

#PBS -M zwu381@gatech.edu
#

#---------------------------------------------------------------------

# Part 2 Computation

#---------------------------------------------------------------------


cd /storage/home/hcoda1/1/zwu381/p-awu36-0/DVAE

module load anaconda3
module load pytorch/1.4
conda activate pivae
conda install --file requirements_pace.txt

python3 train_model.py --cfg ./config/neural/cfg_dkf.ini

