
#!/bin/bash
#---------------------------------------------------------------------

# Part 1 PBS Directives

#---------------------------------------------------------------------

#PBS -N dvae_latent

#PBS -A GT-awu36

#PBS -l walltime=8:00:00

#PBS -l nodes=2:ppn=2

#PBS -q inferno

#PBS -o results.out

#PBS -j oe

#PBS -m abe

#PBS -M zwu381@gatech.edu
#

#---------------------------------------------------------------------

# Part 2 Computation

#---------------------------------------------------------------------


cd /storage/home/hcoda1/1/zwu381/p-awu36-0/DVAE

module load anaconda3/2019.10
module load pytorch/1.4
conda activate d-vae

python3 train_model.py --cfg ./config/neural/cfg_dkf_lag1.ini
python3 train_model.py --cfg ./config/neural/cfg_dkf_lag5.ini
python3 train_model.py --cfg ./config/neural/cfg_dkf_lag10.ini
python3 train_model.py --cfg ./config/neural/cfg_dkf_lag20.ini

